services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/postgres
      - DB_USER=shingchunho
      - DB_PASSWORD=ccASijJwck9d
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: shingchunho
      POSTGRES_PASSWORD: ccASijJwck9d
    ports:
      - "5432:5432"
